### ISSUE TITLE
outdir vs outfile

### ISSUE THREAD

**Issue by moranbw** [jgoz/esbuild-plugins#132]
Hi really liking `esbd`...was about to write something very similar before I stumbled upon this project.  Seems like a nice alternative to `ts-node` and `tsm` without leaving the node ecosystem for something like Deno or Bun.

Quick question: you seem to only support the esbuild `outdir` option, and not `outfile`.  If I try to use `outfile` in my `configure` object, it does not work because it seems like you update `outdir` if it does not exist:

```
function updateConfig(config: EsbdConfig, logLevel: LogLevel): ResolvedEsbdConfig {
  config.absWorkingDir ??= process.cwd();
  config.logLevel = logLevel;
  config.outdir ??= path.join(config.absWorkingDir, 'dist');
  config.plugins ??= [];

  return config as ResolvedEsbdConfig;
}
```

So esbuild will fail since both are set.  Any reason for this?  Not a huge deal, just curious.

**Comment by jgoz** [comment]
Hi, thank you!

The short answer is that I have never used outfile and conveniently ignored its existence. It might be possible to support it for Node projects, but it doesn't really make sense for web projects IMO. Especially the "HTML entrypoint" stuff, which really needs an output directory.

Also, using outfile instead of outdir would prevent other features like `copy` from being usable even for Node projects, since they rely on an output directory.

I'm not opposed to having basic support for it, but it also doesn't really "fit in" with the project nicely.

**Comment by moranbw** [comment]
Thanks for the response -- that makes sense.  After digging a bit deeper in esbuild config options, I can actually achieve what I want.

I am bundling node projects for cleaner use in AWS Lambda, and I am really just using one entrypoint and one output file (hence my use of `outfile`).  It was annoying me a little bit that my output with `outdir` was `dist/src/index.js` rather than just `dist/index.js`.  This seems to be working for me now, though:

```
entryPoints: [{ in: 'src/index.ts', out: 'index.js' }],
outdir: './dist',
```
